// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6cwThT_7Nk6HdZ252xRbFAzOfth7kqQ',
    appId: '1:733179375716:web:e2fe8c8fd10226a2976f71',
    messagingSenderId: '733179375716',
    projectId: 'bildirim-merkezi-df56e',
    authDomain: 'bildirim-merkezi-df56e.firebaseapp.com',
    storageBucket: 'bildirim-merkezi-df56e.firebasestorage.app',
    measurementId: 'G-Q09KFPVS7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGZ7YNnnz0rjAM9mhh64Y91IJh8wORQKY',
    appId: '1:733179375716:android:45ed13c6e0d46c7b976f71',
    messagingSenderId: '733179375716',
    projectId: 'bildirim-merkezi-df56e',
    storageBucket: 'bildirim-merkezi-df56e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIjIahGH2DPaG9MhR6lYnBoYDOhYVmdg',
    appId: '1:733179375716:ios:8e2b8611e6127f92976f71',
    messagingSenderId: '733179375716',
    projectId: 'bildirim-merkezi-df56e',
    storageBucket: 'bildirim-merkezi-df56e.firebasestorage.app',
    iosBundleId: 'com.example.bildirimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIjIahGH2DPaG9MhR6lYnBoYDOhYVmdg',
    appId: '1:733179375716:ios:8e2b8611e6127f92976f71',
    messagingSenderId: '733179375716',
    projectId: 'bildirim-merkezi-df56e',
    storageBucket: 'bildirim-merkezi-df56e.firebasestorage.app',
    iosBundleId: 'com.example.bildirimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6cwThT_7Nk6HdZ252xRbFAzOfth7kqQ',
    appId: '1:733179375716:web:48c8cdcbef46a262976f71',
    messagingSenderId: '733179375716',
    projectId: 'bildirim-merkezi-df56e',
    authDomain: 'bildirim-merkezi-df56e.firebaseapp.com',
    storageBucket: 'bildirim-merkezi-df56e.firebasestorage.app',
    measurementId: 'G-QKGGHPLH3Y',
  );
}
